version: '2.1'
services:
  etcd:
    image: docker.io/bitnami/etcd:3.5.1
    container_name: etcd
    restart: always
    ports:
      - '2379:2379'
      - '2380:2380'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - 'etcd_data:/bitnami/etcd'
volumes:
  etcd_data:
    driver: local